name: CheckTestsAndLint
on:
  push:
    branches: -master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install dependencies
        run: bun ci --legacy-peer-deps
      - name: Lint
        run: bun run lint
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install dependencies
        run: bun ci --legacy-peer-deps
      - name: Test
        run: bun run test
